stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

services:
  - docker:20.10.16-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


build_backend:
  stage: build
  image: node:19
  script:
    - cd backend
    - docker build -t backend .
    - docker tag backend $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG
  only:
    - branches

build_frontend:
  stage: build
  image: node:19
  script:
    - cd frontend
    - docker build -t frontend .
    - docker tag frontend $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG
  only:
    - branches


push_backend:
  stage: push
  script:
    - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG
  only:
    - branches

push_frontend:
  stage: push
  script:
    - docker push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG
  only:
    - branches
