version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    env_file: "./mysql/.env"    
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - custom-bridge

  backend:
    build: ./backend
    container_name: backend-container
    env_file: "./backend/.env"
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    volumes:
      - ./backend/static:/app/static
      - ./backend/src:/app/src
    networks:
      - custom-bridge

  frontend:
    build: ./frontend
    container_name: frontend-container
    env_file: "./frontend/.env"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
    networks:
      - custom-bridge

volumes:
  mysql-data:

networks:
  custom-bridge:
    driver: bridge

